QSerialDevice: AbstractSerial Class Reference
AbstractSerial Class Reference
Class AbstractSerial provides the minimum and adequate interface for working with serial devices.
Public Types
enum BaudRate {
BaudRate50 = 50, BaudRate75 = 75, BaudRate110 = 110, BaudRate134 = 134,
BaudRate150 = 150, BaudRate200 = 200, BaudRate300 = 300, BaudRate600 = 600,
BaudRate1200 = 1200, BaudRate1800 = 1800, BaudRate2400 = 2400, BaudRate4800 = 4800,
BaudRate9600 = 9600, BaudRate14400 = 14400, BaudRate19200 = 19200, BaudRate38400 = 38400,
BaudRate56000 = 56000, BaudRate57600 = 57600, BaudRate76800 = 76800, BaudRate115200 = 115200,
BaudRate128000 = 128000, BaudRate256000 = 256000
}
enum DataBits { DataBits5 = 5, DataBits6 = 6, DataBits7 = 7, DataBits8 = 8 }
enum Parity {
ParityNone = 1, ParityOdd = 2, ParityEven = 3, ParityMark = 4,
ParitySpace = 5
}
enum StopBits { StopBits1 = 1, StopBits1_5 = 15, StopBits2 = 2 }
enum Flow { FlowControlOff = 1, FlowControlHardware = 2, FlowControlXonXoff = 3 }
enum Status {
ENone = 0, ENoneOpen = 1, ENoneClose = 2, ENoneSetBaudRate = 3,
ENoneSetParity = 4, ENoneSetDataBits = 5, ENoneSetStopBits = 6, ENoneSetFlow = 7,
ENoneSetCharTimeout = 8, EOpen = 15, EDeviceIsNotOpen = 16, EOpenModeUnsupported = 17,
EOpenModeUndefined = 18, EOpenInvalidFD = 19, EOpenOldSettingsNotSaved = 20, EOpenGetCurrentSettings = 21,
EOpenSetDefaultSettings = 22, EDeviceIsOpen = 23, ECloseSetOldSettings = 24, ECloseFD = 25,
EClose = 26, ESetBaudRate = 32, ESetDataBits = 33, ESetParity = 34,
ESetStopBits = 35, ESetFlowControl = 36, ESetCharIntervalTimeout = 37, EBytesAvailable = 40,
ESetDtr = 41, ESetRts = 42, ELineStatus = 43, EWaitReadyReadIO = 44,
EWaitReadyReadTimeout = 45, EWaitReadyWriteIO = 46, EWaitReadyWriteTimeout = 47, EReadDataIO = 48,
EWriteDataIO = 49, EFlush = 50
}
enum LineStatus
Signals
void signalStatus (const QString &status, QDateTime current)
Public Member Functions
AbstractSerial (QObject *parent=0)
virtual ~AbstractSerial ()
void setDeviceName (const QString &deviceName)
QString deviceName () const
bool setBaudRate (BaudRate baudRate)
bool setBaudRate (const QString &baudRate)
QString baudRate () const
QStringList listBaudRate () const
bool setDataBits (DataBits dataBits)
bool setDataBits (const QString &dataBits)
QString dataBits () const
QStringList listDataBits () const
bool setParity (Parity parity)
bool setParity (const QString &parity)
QString parity () const
QStringList listParity () const
bool setStopBits (StopBits stopBits)
bool setStopBits (const QString &stopBits)
QString stopBits () const
QStringList listStopBits () const
bool setFlowControl (Flow flow)
bool setFlowControl (const QString &flow)
QString flowControl () const
QStringList listFlowControl () const
bool setCharIntervalTimeout (int msecs=10)
int charIntervalTimeout () const
bool setDtr (bool set)
bool setRts (bool set)
ulong lineStatus ()
bool open (OpenMode mode)
void close ()
bool flush ()
bool reset ()
qint64 bytesAvailable () const
bool waitForReadyRead (int msecs=5000)
bool waitForBytesWritten (int msecs=5000)
void enableEmitStatus (bool enable)
Protected Member Functions
qint64 readData (char *data, qint64 maxSize)
qint64 writeData (const char *data, qint64 maxSize)
Detailed Description
Class AbstractSerial provides the minimum and adequate interface for working with serial devices.
Class to work with serial devices (ports). This class is a cross-platform low-level library, which is based on Qt4, and respectively, can be used to create applications Qt4.
Implementation of this class structure is broadly similar to the implementation of the supply QAbstractSocket Qt4, ie corresponds to the ideology of public/private classes (pimpl), and this class is a descendant of QIODevice and respectively inherits from him all his methods.
The work of this class with a serial device is in asynchronous mode!
When used in a variety of operating systems - used their native system API:
On Windows NT/2K/XP family, etc. use Win32 API.
In the POSIX like OS system calls used by POSIX.
Getting Started with the class should begin with the creation of an object instance AbstractSerial.
Example:
        ...
        AbstractSerial *serialDevice = new AbstractSerial()
        ...
Device parameters, such as:
speed, data bits, parity, stop bits, flow control, timed character (in milliseconds) - always accepted by default, respectively: 9600 8 N 1 10ms! Also by default, be assigned to the object first name actually exists in the system device.
        Operating system:          The device name default:
        Windows                    "COM1"
        IRIX                       "/dev/ttyf1"
        HPUX                       "/dev/tty1p0"
        SOLARIS                    "/dev/ttya"
        FREEBSD                    "/dev/ttyd1"
        LINUX                      "/dev/ttyS0"
        <default>                  "/dev/ttyS0"
Next, you need a device (object) to assign a name actually exists in the system:
void AbstractSerial::setDeviceName(const QString &deviceName).
To open a serial device, you must call the method:
bool AbstractSerial::open(QIODevice::OpenMode).
If successful, the opening of this method returns true. Class AbstractSerial supports only option open QIODevice as: OpenMode::ReadOnly, OpenMode::WriteOnly, OpenMode::ReadWrite, while for the correct operation mode to add OpenMode::Unbuffered Example:
        ...
        //this example open device as ReadOnly
        bool ret = serialDevice->open(QIODevice::ReadOnly | QIODevice::Unbuffered);
        ...
Note:
the serial device always opens with the parameters for default: 9600 8 N 1 10ms
To close the serial device need to call the method:
void AbstractSerial::close()
Once the device successfully opened, you are ready to configure it. To do this, use the following methods:
bool AbstractSerial::setBaudRate(AbstractSerial::BaudRate) - sets the speed of data exchange.
With the success of the method returns true.
bool AbstractSerial::setDataBits(AbstractSerial::DataBits) - sets the number of data bits.
With the success of the method returns true.
bool AbstractSerial::setParity(AbstractSerial::Parity) - sets the parity.
With the success of the method returns true.
bool AbstractSerial::setStopBits(AbstractSerial::StopBits) - sets the number of stop bits.
With the success of the method returns true.
bool AbstractSerial::setFlowControl(AbstractSerial::Flow) - sets the control flow control.
With the success of the method returns true.
bool AbstractSerial::setCharIntervalTimeout(int msecs) - sets the waiting time of arrival character when reading data.
With the success of the method returns true.
Since device operates in asynchronous mode, it is sufficient for a confident reading of data to select only experienced by this parameter timeout. This option is the only option when reading dannh, it just depends on the speed and choose/calculate it can be empirically. Typically, for sure receive sufficient magnitude 10ms for all speeds. It simplifies work with a serial device.
To read/write data to the port is recommended to use the following methods:
QByteArray AbstractSerial::read(qint64 maxSize) - reads data from the serial device.
Method read() inherited from QIODevice. Theoretically, the size maxSize is not limited, because method reads the available number of bytes in parts. Really class AbstractSerial implemented a secure method: qint64 readData(char *data, qint64 maxlen) in which defines all the logic of reading data from the device. Reading data is carried out in such a way that not lose data!
Note:
work method: QByteArray readAll() not tested. It is recommended to use the method read()
qint64 AbstractSerial::write(const QByteArray &byteArray) - writes data to a serial device.
Method write() inherited from QIODevice. Theoretically, the size byteArray is not limited, because method records data in parts. After recording all data in the device emitted a signal bytesWritten(qint64 bytes). Really class AbstractSerial implemented a secure method: qint64 writeData(const char *data, qint64 maxSize) in which defines all the logic of writing data to the device.
In anticipation of the return data in the serial device using the method:
bool AbstractSerial::waitForReadyRead(int msecs)
The method waits for the arrival time msecs in the receive buffer of the serial device at least one byte of data. If successful, the expectation (when B came to a timeout msecs) method emits a signal readyRead() and returns true.
To clear the buffer of the serial device used methods:
bool AbstractSerial::flush() - forced forward to the completion of read/write and at their end clears the I/O queues
bool AbstractSerial::reset() - not waiting for the completion of I/O clears the serial buffer device.
To control lines DTR and RTS methods are used:
bool AbstractSerial::setDtr(bool set)
bool AbstractSerial::setRts(bool set)
If successful, the method returns true.
For the status lines CTS, DSR, DCD, RI, RTS, DTR, ST, SR method is used:
ulong AbstractSerial::lineStatus(). The method returns an encoded value status lines bitwise OR (see. enum AbstractSerial::LineStatus).
        CTS     0x01
        DSR     0x02
        DCD     0x04
        RI      0x08
        RTS     0x10
        DTR     0x20
        ST      0x40
        SR      0x80
For the current number of bytes in the receive buffer the serial device is ready for reading method is used:
qint64 AbstractSerial::bytesAvailable().
To enable/disable the radiation signal signalStatus() method is used:
void AbstractSerial::enableEmitStatus(bool enable).
For a list of names for serial devices available in the system, as well as tracking them use the class: SerialDeviceWatcher.
Class AbstractSerial implements the following signals:
void AbstractSerial::readyRead() - emitted once at the arrival in the receiving buffer device at least one byte of data.
Event of the arrival of data is controlled in the message loop. When comes the next part of the data (or B) - the signal is not radiated! In order to re-emitted signal must read the data from the buffer by the method read() or reset the buffer reset()! Also, this signal is emitted each time a successful call to the method waitForReadyRead().
void AbstractSerial::bytesWritten(qint64 bytes) - emitted when the successful completion of the method write().
void AbstractSerial::signalStatus(const QString &status, QDateTime current) - carries information about the current status of the serial devices, as well as time and date of status. Is emitted whenever the following actions:
The performance of methods open(), close()
On error when configuring
On error reading/writing, etc.
The emission signal can be switched on/off when you call: AbstractSerial::enableEmitStatus(bool enable).
Warning:
In this description lists all the methods implemented in the classroom. If you do not specify the method implemented - that means its value is immaterial.
By default, the class is configured in such a way as to write to the console debug messages. To disable these messages in the console - need to comment out in the *. cpp files, a line like:
    ...
    #define NATIVESERIALENGINE_DEBUG
    ...
and re-rebuild library.
Version:
0.2.0
Author:
Denis Shienkov
ICQ : 321789831
e-mail : scapig2@yandex.ru
Note:
In a version 0.1.0. work of library was tested by author only with: Windows XP Sp3 Pro and Archlinux x86_64.
In theory must a library be supported such OS as: all of family of Windows Nt/2k/xp, and also POSIX compatible.
Definition at line 33 of file abstractserial.h.
Member Enumeration Documentation
enum AbstractSerial::BaudRate
In this enumeration of all supporting classes AbstractSerial speed.
Enumerator:
BaudRate50
speed 50 bauds
BaudRate75
speed 75 bauds
BaudRate110
speed 110 bauds
BaudRate134
speed 134 bauds
BaudRate150
speed 150 bauds
BaudRate200
speed 200 bauds
BaudRate300
speed 300 bauds
BaudRate600
speed 600 bauds
BaudRate1200
speed 1200 bauds
BaudRate1800
speed 1800 bauds
BaudRate2400
speed 2400 bauds
BaudRate4800
speed 4800 bauds
BaudRate9600
speed 9600 bauds
BaudRate14400
speed 14400 bauds
BaudRate19200
speed 19200 bauds
BaudRate38400
speed 38400 bauds
BaudRate56000
speed 56000 bauds
BaudRate57600
speed 57600 bauds
BaudRate76800
speed 76800 bauds
BaudRate115200
speed 115200 bauds
BaudRate128000
speed 128000 bauds
BaudRate256000
speed 256000 bauds
Definition at line 48 of file abstractserial.h.
enum AbstractSerial::DataBits
In this enumeration of all supporting classes AbstractSerial number of bits of data.
Enumerator:
DataBits5
5 data bits
DataBits6
6 data bits
DataBits7
7 data bits
DataBits8
8 data bits
Definition at line 76 of file abstractserial.h.
enum AbstractSerial::Flow
In this enumeration of all supporting classes AbstractSerial modes of flow control.
Enumerator:
FlowControlOff
flow control off
FlowControlHardware
flow control hardware
FlowControlXonXoff
flow control Xon/Xoff
Definition at line 106 of file abstractserial.h.
enum AbstractSerial::LineStatus
In this enumeration of all supporting classes AbstractSerial state lines of port: CTS, DSR, DCD, RI, RTS, DTR, ST, SR (see RS-232 standard, etc.)
Definition at line 169 of file abstractserial.h.
enum AbstractSerial::Parity
In this enumeration of all supporting classes AbstractSerial types of control parity.
Enumerator:
ParityNone
parity off (none)
ParityOdd
odd parity
ParityEven
even parity
ParityMark
mark parity
ParitySpace
space parity
Definition at line 86 of file abstractserial.h.
enum AbstractSerial::Status
In this enumeration of all supporting classes AbstractSerial job status.
Enumerator:
ENone
no errors
ENoneOpen
open without errors
ENoneClose
closed without errors
ENoneSetBaudRate
speed is set correctly
ENoneSetParity
parity set correctly
ENoneSetDataBits
data bits are installed correctly
ENoneSetStopBits
stop bits are set correctly
ENoneSetFlow
flow control is set correctly
ENoneSetCharTimeout
timed character set without errors
EOpen
error opening
EDeviceIsNotOpen
device is not open
EOpenModeUnsupported
open mode is not supported
EOpenModeUndefined
open mode is undefined
EOpenInvalidFD
invalid handle
EOpenOldSettingsNotSaved
problem of preserving the old settings when you open
EOpenGetCurrentSettings
error obtaining the current settings when you open
EOpenSetDefaultSettings
error installing the default settings when you open
EDeviceIsOpen
device is already open
ECloseSetOldSettings
problem of preserving the old settings when you close
ECloseFD
error when closing the descriptor
EClose
error when closing (general)
ESetBaudRate
error when installing speed
ESetDataBits
error when installing count data bits
ESetParity
error when installing parity
ESetStopBits
error when installing count stop bit
ESetFlowControl
error when installing flow control
ESetCharIntervalTimeout
rror when installing the timeout symbol
EBytesAvailable
failed to get a count bytes ready to read
ESetDtr
error when installing DTR
ESetRts
error when installing RTS
ELineStatus
error getting status lines
EWaitReadyReadIO
I/O error when waiting for data reception
EWaitReadyReadTimeout
error expiration time for waiting to receive data
EWaitReadyWriteIO
I/O error when waiting for data
EWaitReadyWriteTimeout
error when waiting for the expiration time data
EReadDataIO
error reading data
EWriteDataIO
error data
EFlush
error when clearing the queue buffers
Definition at line 115 of file abstractserial.h.
enum AbstractSerial::StopBits
In this enumeration of all supporting classes \ a AbstractSerial number of stop bits.
Enumerator:
StopBits1
one stop bit
StopBits1_5
half stop bit
StopBits2
two stop bit
Definition at line 97 of file abstractserial.h.
Constructor & Destructor Documentation
AbstractSerial::AbstractSerial (QObject * parent = 0) [explicit]
Default constructor. Creates an object, associated with the real serial device in the system. For example: for Windows - it COM1, COM2 ... COMn, for Linux - it /dev/ttyS0, /dev/ttyS1 etc
Note:
If not to specify (to skip) the parameter of devicename in a constructor - that by default the name will be appropriated a device = DEFAULT_DEVICE_NAME
        Operating system:       Name DEFAULT_DEVICE_NAME:
        Windows                 "COM1"
        IRIX                    "/dev/ttyf1"
        HPUX                    "/dev/tty1p0"
        SOLARIS                 "/dev/ttya"
        FREEBSD                 "/dev/ttyd1"
        LINUX                   "/dev/ttyS0"
        <default>               "/dev/ttyS0"
Definition at line 511 of file abstractserial.cpp.
AbstractSerial::~AbstractSerial () [virtual]
Default destructor.
Definition at line 524 of file abstractserial.cpp.
Member Function Documentation
QString AbstractSerial::baudRate () const
Returns baud rate as a string which a serial device is configured with.
Returns:
baud rate as an string QString
0 - in the case of error
Definition at line 703 of file abstractserial.cpp.
qint64 AbstractSerial::bytesAvailable () const
A byte returns an amount ready for reading,
Returns:
n - is an amount byte at success
-1 - in the case of error
Definition at line 1341 of file abstractserial.cpp.
Referenced by waitForReadyRead().
int AbstractSerial::charIntervalTimeout () const
Returns time of expectation of arrival of character in the receiving buffer of serial device which a serial device is configured with.
Returns:
Time of expectation of arrival of character, in msek
0 - in the case of error
Definition at line 1145 of file abstractserial.cpp.
void AbstractSerial::close ()
Closes a serial device
Definition at line 1271 of file abstractserial.cpp.
References EClose, and ENoneClose.
QString AbstractSerial::dataBits () const
Returns data bits as a string which a serial device is configured with.
Returns:
data bits as an string QString
0 - in the case of error
Definition at line 797 of file abstractserial.cpp.
QString AbstractSerial::deviceName () const
Returns the serial device which an object is configured with name.
Returns:
Serial device with which an object is configured as Qstring name
0 in the case of error
Note:
Uses this method is possible at any moment after creation of object, I.e. it is unimportant openly really device or not.
Definition at line 633 of file abstractserial.cpp.
void AbstractSerial::enableEmitStatus (bool enable)
On or Off the flag of emitting of signal of signalStatus()
Parameters:
[in] enable - desired value of flag
Note:
if:
enable = true - it means that to On emitting of signal of signalStatus()
enable = false - it means that to Off emitting of signal of signalStatus()
Definition at line 1544 of file abstractserial.cpp.
QString AbstractSerial::flowControl () const
Returns flow control as a string which a serial device is configured with.
Returns:
flow control as an string QString
0 - in the case of error
Definition at line 1079 of file abstractserial.cpp.
bool AbstractSerial::flush ()
Clears the buffers of serial device.
Returns:
true - at success
false - at an error
Definition at line 1293 of file abstractserial.cpp.
References EDeviceIsNotOpen, and EFlush.
ulong AbstractSerial::lineStatus ()
Returned the status lines CTS, DSR, DCD, RI, RTS, DTR, ST, SR. The method returns an encoded value status lines bitwise OR.
Returns:
true - at success
false - at an error
Definition at line 1211 of file abstractserial.cpp.
References EDeviceIsNotOpen, and ELineStatus.
QStringList AbstractSerial::listBaudRate () const
Returns the text list of all of speeds (baud rates), supported the class of Abstractserial.
Returns:
List of speeds (baud rates) as Qstringlist
Definition at line 728 of file abstractserial.cpp.
QStringList AbstractSerial::listDataBits () const
Returns the text list of all of data bits, supported the class of Abstractserial.
Returns:
List of data bits as Qstringlist
Definition at line 822 of file abstractserial.cpp.
QStringList AbstractSerial::listFlowControl () const
Returns the text list of all of flow controls, supported the class of Abstractserial.
Returns:
List of flow controls as Qstringlist
Definition at line 1104 of file abstractserial.cpp.
QStringList AbstractSerial::listParity () const
Returns the text list of all of paritys, supported the class of Abstractserial.
Returns:
List of paritys as Qstringlist
Definition at line 916 of file abstractserial.cpp.
QStringList AbstractSerial::listStopBits () const
Returns the text list of all of stop bits, supported the class of Abstractserial.
Returns:
List of stop bits as Qstringlist
Definition at line 1010 of file abstractserial.cpp.
bool AbstractSerial::open (OpenMode mode)
Opens a serial device.
Parameters:
[in] mode - mode of opening of serial device
Returns:
true - at success
false - in the case of error
Note:
A serial device is opened with parameters by default in the mode 9600 8 N 1, and 10 ms time of expectation of character. Since a device is successful openly - it is possible to proceed to his configuring!
A device correctly works ONLY at the use of the mode of QIODevice::Unbuffered
Definition at line 1244 of file abstractserial.cpp.
References EDeviceIsOpen, ENoneOpen, and EOpen.
QString AbstractSerial::parity () const
Returns parity as a string which a serial device is configured with.
Returns:
parity as an string QString
0 - in the case of error
Definition at line 891 of file abstractserial.cpp.
qint64 AbstractSerial::readData (char * data, qint64 maxSize) [protected]
Reads the package of data from the input buffer of serial device.
Parameters:
[out] *data - a pointer to the buffer (array) in which takes a place reading of package of data
[in] maxSize - an amount is a byte, which must be read
Returns:
n - an amount is real read byte - at success
-1 - in the case of error
Definition at line 1450 of file abstractserial.cpp.
References EReadDataIO.
bool AbstractSerial::reset ()
Reset the buffers of serial device.
Returns:
true - at success
false - at an error
Definition at line 1316 of file abstractserial.cpp.
References EDeviceIsNotOpen.
bool AbstractSerial::setBaudRate (const QString & baudRate)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets a baud rate for a serial device
Parameters:
[in] baudRate - desired baud rate of serial device as an string
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of BaudRate will be ignored otherwise)
Definition at line 680 of file abstractserial.cpp.
References ENoneSetBaudRate, and setBaudRate().
bool AbstractSerial::setBaudRate (BaudRate baudRate)
Sets a baud rate for a serial device
Parameters:
[in] baudRate - desired baud rate of serial device from enumeration.
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of BaudRate will be ignored otherwise)
Definition at line 653 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetBaudRate, and ESetBaudRate.
Referenced by setBaudRate().
bool AbstractSerial::setCharIntervalTimeout (int msecs = 10)
Fixes time expectation of arrival of character in the receiving buffer of serial device.
Parameters:
[in] msecs - desired time of expectation of arrival of character, in msek
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of msecs will be ignored otherwise)
Definition at line 1123 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetCharTimeout, and ESetCharIntervalTimeout.
bool AbstractSerial::setDataBits (const QString & dataBits)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets a data bits for a serial device
Parameters:
[in] dataBits - desired data bits of serial device as an string
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of dataBits will be ignored otherwise)
Definition at line 774 of file abstractserial.cpp.
References ENoneSetDataBits, and setDataBits().
bool AbstractSerial::setDataBits (DataBits dataBits)
Sets a data bits for a serial device
Parameters:
[in] dataBits - desired data bits of serial device from enumeration.
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of dataBits will be ignored otherwise)
Definition at line 747 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetDataBits, and ESetDataBits.
Referenced by setDataBits().
void AbstractSerial::setDeviceName (const QString & deviceName)
Appropriates the created object the serial device with which it is necessary to work name.
Parameters:
[in] deviceName - serial device, really present in the system name.
For example: for Windows - it COM1, COM2 ... COMn, for Linux - it /dev/ttyS0, /dev/ttyS1 etc
Note:
Uses this method is necessary only BEFORE opening of device!
Definition at line 615 of file abstractserial.cpp.
bool AbstractSerial::setDtr (bool set)
Sets DTR line an state "high" or "low"
Parameters:
[in] set - desired state of line DTR
Returns:
true - at success
false - at an error
Definition at line 1163 of file abstractserial.cpp.
References EDeviceIsNotOpen, and ESetDtr.
bool AbstractSerial::setFlowControl (const QString & flow)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets a flow control bits for a serial device
Parameters:
[in] flow - desired flow of serial device as an string
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of flow will be ignored otherwise)
Definition at line 1056 of file abstractserial.cpp.
References ENoneSetFlow, and setFlowControl().
bool AbstractSerial::setFlowControl (Flow flow)
Sets a flow control for a serial device
Parameters:
[in] flow - desired flow control of serial device from enumeration.
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of flow will be ignored otherwise)
Definition at line 1029 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetFlow, and ESetFlowControl.
Referenced by setFlowControl().
bool AbstractSerial::setParity (const QString & parity)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets a parity for a serial device
Parameters:
[in] parity - desired parity of serial device as an string
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of parity will be ignored otherwise)
Definition at line 868 of file abstractserial.cpp.
References ENoneSetParity, and setParity().
bool AbstractSerial::setParity (Parity parity)
Sets a parity for a serial device
Parameters:
[in] parity - desired parity of serial device from enumeration.
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of parity will be ignored otherwise)
Definition at line 841 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetParity, and ESetParity.
Referenced by setParity().
bool AbstractSerial::setRts (bool set)
Sets DTR line an state "high" or "low"
Parameters:
[in] set - desired state of line RTS
Returns:
true - at success
false - at an error
Definition at line 1188 of file abstractserial.cpp.
References EDeviceIsNotOpen, and ESetRts.
bool AbstractSerial::setStopBits (const QString & stopBits)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Sets a stop bits for a serial device
Parameters:
[in] stopBits - desired stop bits of serial device as an string
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of stopBits will be ignored otherwise)
Definition at line 962 of file abstractserial.cpp.
References ENoneSetStopBits, and setStopBits().
bool AbstractSerial::setStopBits (StopBits stopBits)
Sets a stop bits for a serial device
Parameters:
[in] stopBits - desired stop bits of serial device from enumeration.
Returns:
true - at success
false - at an error
Note:
Uses this method is possible ONLY Since DEVICE was OPENED! (the parameter of stopBits will be ignored otherwise)
Definition at line 935 of file abstractserial.cpp.
References EDeviceIsNotOpen, ENoneSetStopBits, and ESetStopBits.
Referenced by setStopBits().
AbstractSerial::signalStatus (const QString & status, QDateTime current) [signal]
This signal is emitted every time at the change of status of object of Abstractserial at the call of his methods from the sections of public and protected. The change of status can be caused the followings reasons:
at errors configuring of device
at his opening/closing
at the errors of reading/writting of data etc.
Note:
Applying this signal is possible in GUI application for example thus:
        ...
        connect( this, SIGNAL(signalStatus(const QString &, QDateTime)), widget, SLOT(update(const QString &, QDateTime)) );
        ...
        void widget::update(const QString &msg, QDateTime dt)
        {
            ...
            QString dtString = dt.time().toString();
            QString str = msg + ", in time:" + dtString;
            ...
            listWidget->addItem(str);
            ...
        }
QString AbstractSerial::stopBits () const
Returns stop bits as a string which a serial device is configured with.
Returns:
stop bits as an string QString
0 - in the case of error
Definition at line 985 of file abstractserial.cpp.
bool AbstractSerial::waitForBytesWritten (int msecs = 5000)
Expects a care from the output buffer of serial device of the last character in the flow of set time.
Note:
In this version of library this method while is not realized.
Definition at line 1430 of file abstractserial.cpp.
bool AbstractSerial::waitForReadyRead (int msecs = 5000)
Expects arrival in the entrance buffer of serial device of even one byte of data in the flow of set time. The signal of readyRead() emitted at successful implementation().
Parameters:
[in] msecs - time in the flow of which is expected arrival of character, in msek
Returns:
true - at success
false - in the case of error or at a timeout
Definition at line 1393 of file abstractserial.cpp.
References bytesAvailable(), EDeviceIsNotOpen, and EWaitReadyReadTimeout.
qint64 AbstractSerial::writeData (const char * data, qint64 maxSize) [protected]
Passes the package of data in the output buffer of serial device. The signal of bytesWritten() emitted at successful implementation.
Parameters:
[in] *data - a pointer to the buffer (array) from which takes a place write of package of data
[in] maxSize - an amount is a byte, which must be write
Returns:
n - an amount is real write byte - at success
-1 - in the case of error
Definition at line 1474 of file abstractserial.cpp.
References EWriteDataIO.
The documentation for this class was generated from the following files:
qserialdevice/abstractserial.h
qserialdevice/abstractserial.cpp